
  0%|                                                                                                                                         | 0/105160 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\ASUS TUF\Downloads\Diffusion-LM\train_gpt2_e2e.py", line 66, in <module>
    trainer.train()
  File "C:\Users\ASUS TUF\miniconda3\envs\diff-lm\lib\site-packages\transformers\trainer.py", line 1272, in train
    tr_loss += self.training_step(model, inputs)
  File "C:\Users\ASUS TUF\miniconda3\envs\diff-lm\lib\site-packages\transformers\trainer.py", line 1734, in training_step
    loss = self.compute_loss(model, inputs)
  File "C:\Users\ASUS TUF\miniconda3\envs\diff-lm\lib\site-packages\transformers\trainer.py", line 1776, in compute_loss
    loss = outputs["loss"] if isinstance(outputs, dict) else outputs[0]
  File "C:\Users\ASUS TUF\miniconda3\envs\diff-lm\lib\site-packages\transformers\file_utils.py", line 1738, in __getitem__
    return inner_dict[k]
KeyError: 'loss'